### PR TITLE
Various parts do not share the same Redis configuration and default to localhost

### PR DESCRIPTION
**Pull request by patroza**
The creation of kue queues do not adhere to the configured Redis configuration and instead default to localhost.

This PR addresses that problem.

### CODE REVIEW

**Comment by korbinianfritsch** [comment]
+1, works for me as well.
Thanks for fixing this, @patroza !

**Comment by michaelkantor** [comment]
Thanks @patroza and @korbinianfritsch I've npm published this, BUT:

1. You added a breaking change, so this is now version 2.0.0; I've not gone through and updated the libraries that depend on this to use 2.0.0, so you should be careful around that.
2. I've had to add in specific engine dependencies due to the use of Object.assign (this shouldn't affect you, but is worth keeping in mind when submitting PRs that use Object.assign)

**Comment by korbinianfritsch** [comment]
@michaelkantor Thank you for merging the change and the additional information you provided.

**Comment by patroza** [comment]
@michaelkantor thanks for merging!

**Pull request merged**
